#!/bin/sh
# @name Deploy
# @description A tool for creating and updating remote sites using git and node.js
# @author Charlie Rudenstål <charlie4@gmail.com>
#
# Place this script on the client
#
# Creates a new virtualhost setting and checkouts the repository using GIT
#     $ ./deploy create [virtualhost] [repository] [optional branch]    
#
# Updates the git repository to HEAD (Will remove all local modifications, this is not a merge)
#     $ ./deploy update [virtualhost]
#
# Restart the proxy server (using forever). Will start it if not already running.
#     $ ./deploy restart

REMOTE_HOST=cr@smack.at  # Change edit to match your remote server

case $1 in
	create)
		if [ $# -lt 2 ]; then
			echo "$1: Not enough arguments. Enter a virtualhost and repository (and optionally a branch) for the new site";
			exit 2;
		fi

		if [ $# -lt 3 ]; then
			echo "$1 (Virtualhost $2): Not enough arguments. Enter a repository (and optionally a branch) for the new site";
			exit 2;
		fi

		if [ $# -lt 4 ]; then
			echo "$1: Creating virtualhost for $2 using repository $3"
			BRANCH="master"
		fi

		if [ $# -gt 3 ]; then
			echo "$1: Creating virtualhost for $2 using repository $3 and branch $4"
			BRANCH=$4
		fi


		ssh -T $REMOTE_HOST <<EOI
		
		echo Creating virtual host...
		echo ========================
		echo 

		cd /home/proxy
		sed -e '\$d' server.js > server.tmp.js
		echo 'app.use(express.vhost('\''$2'\'', require('\''/home/cr/$2'\''), app));' >> server.tmp.js
		cp server.tmp.js server.js
		echo 'app.listen(8080);' >> server.js
		
		echo Checking out repository...
		echo ==========================
		echo 

		cd /home/cr/
		mkdir $2
		cd $2
		git init
		git remote add -f origin $3
		git checkout $BRANCH

		echo Restaring proxy server...
		echo =========================
		echo
		
		forever stop /home/proxy/server.js
		forever start /home/proxy/server.js
		exit
EOI
	;;

	update)
		if [ $# -lt 2 ]; then
			echo "$1: Not enough arguments. Enter a virtualhost of the site to update";
			exit 2;
		fi
		
		ssh -T $REMOTE_HOST <<EOI

		echo Updating repository...
		echo ======================
		echo

		cd /home/cr/$2
		git reset --hard HEAD
		git clean -f -d
		git pull

		echo Restaring proxy server...
		echo =========================
		echo

		forever stop /home/proxy/server.js
		forever start /home/proxy/server.js
		exit
EOI
	;;

	restart)
		ssh -T $REMOTE_HOST <<EOI

		echo Restaring proxy server...
		echo =========================
		echo

		forever stop /home/proxy/server.js
		forever start /home/proxy/server.js		
		exit
EOI
	;;

esac