/* 
 * DepoProxy @ https://github.com/charlie-rudenstal/depo/ 
 *
 * Warning: This file is generated by depo.sh from a client (through SSH).
 * When a new virtualhost is added it will: 
 * 1. Remove the last line (app.listen()), 
 * 2. Append a new app.use() statement
 * 3. Append app.listen() again *
 *
 * Virtual hosts that depo.sh generates looks something like this:
 * app.use(express.vhost('beta.example.org', require('/home/cr/beta.example.org').app));
 *
 * You may modify this file on your own risk, but be 
 * sure to leave no newlines on the end of the file.
 */

/*global require */

var express = require("express");
var app = express();
app.listen(8080);